N. Eldad Okoyo
425-xxx-xxxx
_____________YOUR EMAIL____________@gmail.com
linkedin.com/in/joshmadakor 

INTRO

Hello, my name is Eldad Okoyo and I'm currently making the transition from the food services industry into the Information Technology field with a focus on Systems Engineering. I've been doing everything I can to improve my skills and gain exposure, and have produced and released content that is currently in use today (see below). Thank you for reviewing my resume!

EXPERIENCE

System Administrator / Content Creator	09/2019 - Present
Company:	JTech LLC - jtech.io
YouTube:	youtube.com/jtech.io
Developed of content for, as well as performed the following tasks:
Active Directory Administration on Server 2019:
PowerShell: Automated provision, maintaining, and deprovisioning user accounts
Implementation and management of Group Policy Objects
Security Group maintenance and administration
Backup administrator using Windows native backup utilities
Implementation and maintenance of Windows DNS and DHCP services
Configuration of Windows File Servers with implementation of quotas and NTFS permissions

Shift Lead		09/2018 - 09/2019
Company:	McDonald's
Regularly performed open and close operations at our location
Managed inventory for foods, which included forecasting for special events and holidays
Received awards for "Best Accuracy" in 2019 and 2020
Acted as designated trainer for newly onboarded staff

EDUCATION

Windows Server Administration	Pluralsight.com, 2020
Active Directory and Group Policy	Pluralsight.com, 2019
Networking in Windows Server	Pluralsight.com, 2019
GED (General Education Degree)	Walla Walla CC, 2002
